# Generated by Django 3.1.2 on 2020-10-16 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_auto_20201015_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="link_to_cover",
            field=models.URLField(
                blank=True, verbose_name="Link to book cover"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.IntegerField(
                blank=True,
                validators=[django.core.validators.MaxValueValidator(2020)],
                verbose_name="Publication date",
            ),
        ),
    ]
