# Generated by Django 3.1.2 on 2020-10-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_auto_20201016_1047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_language",
            field=models.CharField(
                help_text="Prosze podać skrót (zgodnie z ISO) języka w jakim napisana jest książka.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="link_to_cover",
            field=models.URLField(
                blank=True,
                help_text="Pełny link zaczynający się od http:// lub https://",
                verbose_name="Link to book cover",
            ),
        ),
    ]
