# Generated by Django 3.1.2 on 2020-10-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_auto_20201018_1832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_language",
            field=models.CharField(
                help_text="Prosze podać skrót (zgodnie z ISO) języka w jakim napisana jest książka.",
                max_length=3,
            ),
        ),
    ]
