# Generated by Django 3.1.2 on 2020-10-18 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_auto_20201019_0032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.IntegerField(
                blank=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2020),
                ],
                verbose_name="Publication date",
            ),
        ),
    ]
