# Generated by Django 3.1.2 on 2020-10-19 08:17

from django.db import migrations, models

import books.models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_auto_20201019_0036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True,
                max_length=256,
                unique=True,
                validators=[books.models.ISBN_validator],
                verbose_name="ISBN",
            ),
        ),
    ]
