# Generated by Django 3.1.2 on 2020-10-26 13:47

import books_app.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1), message='Zbyt odległa data'), django.core.validators.MaxValueValidator(limit_value=books_app.models.current_date, message='Książka nie może być z przyszłości.')], verbose_name='Publication date'),
        ),
    ]
